import { describe, it, expect } from "vitest";
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  main,
  stampCargoLock,
  stampCargoToml,
  stampTauriConf,
} from "../../../../scripts/stamp-version.mjs";

// The release pipeline's version stamp (#384). These tests guard the exact
// regression the VA reported: installers shipping as 0.1.0 because nothing
// wrote the released version into the Tauri sources.

const REPO_ROOT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../../../..",
);
const TAURI_DIR = path.join(REPO_ROOT, "apps", "desktop", "src-tauri");

// Fixtures mirror the real files' shapes, shrunk to the load-bearing parts.
// The nested "version" key doesn't exist in today's real file — it's here to
// pin first-occurrence-only semantics against a future plugin config gaining
// one (spec §6).
const TAURI_CONF = `{
  "$schema": "https://example.com/schema.json",
  "productName": "AI Music Companion",
  "version": "0.1.0",
  "identifier": "com.aimusiccompanion.desktop",
  "bundle": {
    "copyright": "Copyright \\u00a9 2026 AI Music Companion"
  },
  "plugins": {
    "someday": { "version": "not-the-app-version" }
  }
}
`;

const CARGO_TOML = `[package]
name = "ai-music-companion"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
`;

const CARGO_LOCK = `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "addr2line"
version = "0.1.0"

[[package]]
name = "ai-music-companion"
version = "0.1.0"
dependencies = [
 "serde",
]

[[package]]
name = "serde"
version = "1.0.219"
`;

describe("stamp-version", () => {
  it("stamps the version into all three files and changes nothing else", () => {
    const conf = stampTauriConf(TAURI_CONF, "2.29.0");
    const toml = stampCargoToml(CARGO_TOML, "2.29.0");
    const lock = stampCargoLock(CARGO_LOCK, "2.29.0");

    expect(JSON.parse(conf).version).toBe("2.29.0");
    expect(toml).toContain('version = "2.29.0"');
    expect(lock).toContain('version = "2.29.0"');

    // Byte-identical apart from the single stamped line.
    expect(conf).toBe(
      TAURI_CONF.replace('"version": "0.1.0"', '"version": "2.29.0"'),
    );
    expect(toml).toBe(
      CARGO_TOML.replace('version = "0.1.0"', 'version = "2.29.0"'),
    );
    // JSON string escapes survive (a JSON.stringify re-emit would lose ©).
    expect(conf).toContain("\\u00a9");
    // Only the TOP-LEVEL version is stamped; a nested "version" key in some
    // future plugin config keeps its value.
    expect(JSON.parse(conf).plugins.someday.version).toBe(
      "not-the-app-version",
    );
  });

  it("stamps only the app's own Cargo.lock block — a dependency sharing the old version keeps it", () => {
    const lock = stampCargoLock(CARGO_LOCK, "2.29.0");
    // addr2line also sat at 0.1.0; it must be untouched.
    expect(lock).toContain('name = "addr2line"\nversion = "0.1.0"');
    expect(lock).toContain('name = "ai-music-companion"\nversion = "2.29.0"');
    expect(lock).toContain('version = "1.0.219"');
  });

  it("leaves inline dependency versions in Cargo.toml alone", () => {
    const toml = stampCargoToml(CARGO_TOML, "2.29.0");
    expect(toml).toContain('tauri = { version = "2", features = [] }');
    expect(toml).toContain('serde = { version = "1", features = ["derive"] }');
  });

  it("never stamps a version line outside [package] — missing package version throws instead", () => {
    // A [package] with no version but a later table with a line-anchored one:
    // stamping that dependency would re-ship 0.1.0 installers silently.
    const noPackageVersion =
      '[package]\nname = "x"\nedition = "2021"\n\n[dependencies.foo]\nversion = "1.0.0"\n';
    expect(() => stampCargoToml(noPackageVersion, "2.29.0")).toThrow(
      /Cargo\.toml/,
    );
    expect(() => stampCargoToml("", "2.29.0")).toThrow(/Cargo\.toml/);
  });

  it("stamps CRLF-encoded Cargo.toml (Windows checkout)", () => {
    const crlf = CARGO_TOML.replace(/\n/g, "\r\n");
    const stamped = stampCargoToml(crlf, "2.29.0");
    expect(stamped).toContain('version = "2.29.0"');
    expect(stamped).toContain('tauri = { version = "2", features = [] }');
  });

  it("is idempotent — restamping the same version is a no-op", () => {
    const once = stampCargoToml(CARGO_TOML, "2.29.0");
    expect(stampCargoToml(once, "2.29.0")).toBe(once);
    const conf = stampTauriConf(TAURI_CONF, "2.29.0");
    expect(stampTauriConf(conf, "2.29.0")).toBe(conf);
    const lock = stampCargoLock(CARGO_LOCK, "2.29.0");
    expect(stampCargoLock(lock, "2.29.0")).toBe(lock);
  });

  it("accepts prerelease versions", () => {
    const dir = makeFixtureTree();
    main("2.29.0-beta.1", dir);
    expect(readConf(dir).version).toBe("2.29.0-beta.1");
  });

  it("throws, naming the file, when a version pattern is missing", () => {
    expect(() => stampTauriConf('{ "productName": "x" }', "2.29.0")).toThrow(
      /tauri\.conf\.json/,
    );
    expect(() => stampCargoToml('[package]\nname = "x"\n', "2.29.0")).toThrow(
      /Cargo\.toml/,
    );
    // A renamed app package must fail the release loudly, not ship 0.1.0.
    expect(() =>
      stampCargoLock(
        '[[package]]\nname = "renamed-app"\nversion = "0.1.0"\n',
        "2.29.0",
      ),
    ).toThrow(/Cargo\.lock/);
  });

  it("rejects a stamp that would break the JSON", () => {
    expect(() =>
      stampTauriConf('not json "version": "0.1.0"', "2.29.0"),
    ).toThrow(/not valid JSON/);
  });

  it("main() rejects missing or non-semver version arguments", () => {
    expect(() => main(undefined as unknown as string, REPO_ROOT)).toThrow(
      /usage/,
    );
    expect(() => main("not-a-version", REPO_ROOT)).toThrow(/not-a-version/);
    expect(() => main("v2.29.0", REPO_ROOT)).toThrow(/usage/); // tag prefix is the caller's to strip
  });

  it("main() stamps a real file tree on disk", () => {
    const dir = makeFixtureTree();
    main("3.1.4", dir);
    expect(readConf(dir).version).toBe("3.1.4");
    expect(readFileSync(tauriPath(dir, "Cargo.toml"), "utf8")).toContain(
      'version = "3.1.4"',
    );
    expect(readFileSync(tauriPath(dir, "Cargo.lock"), "utf8")).toContain(
      'name = "ai-music-companion"\nversion = "3.1.4"',
    );
  });

  it("main() fails when a target file is missing", () => {
    const dir = mkdtempSync(path.join(tmpdir(), "stamp-empty-"));
    expect(() => main("3.1.4", dir)).toThrow(/tauri\.conf\.json/);
  });

  // Drift guard: the patterns must keep matching the REAL repo files. If a
  // refactor renames the package or restructures tauri.conf.json, this fails
  // here instead of in the next release run.
  it("matches the actual repo files", () => {
    const conf = readFileSync(path.join(TAURI_DIR, "tauri.conf.json"), "utf8");
    const toml = readFileSync(path.join(TAURI_DIR, "Cargo.toml"), "utf8");
    const lock = readFileSync(path.join(TAURI_DIR, "Cargo.lock"), "utf8");
    expect(JSON.parse(stampTauriConf(conf, "9.9.9")).version).toBe("9.9.9");
    // The stamped line must sit INSIDE the [package] section, not merely
    // somewhere in the file.
    expect(stampCargoToml(toml, "9.9.9")).toMatch(
      /^\[package\]\n(?:(?!\[)[^\n]*\n)*?version = "9\.9\.9"/m,
    );
    expect(stampCargoLock(lock, "9.9.9")).toContain(
      'name = "ai-music-companion"\nversion = "9.9.9"',
    );
  });
});

function tauriPath(root: string, file: string): string {
  return path.join(root, "apps", "desktop", "src-tauri", file);
}

function readConf(root: string): { version: string } {
  return JSON.parse(
    readFileSync(tauriPath(root, "tauri.conf.json"), "utf8"),
  ) as {
    version: string;
  };
}

function makeFixtureTree(): string {
  const dir = mkdtempSync(path.join(tmpdir(), "stamp-version-"));
  const tauriDir = tauriPath(dir, "");
  mkdirSync(tauriDir, { recursive: true });
  writeFileSync(tauriPath(dir, "tauri.conf.json"), TAURI_CONF);
  writeFileSync(tauriPath(dir, "Cargo.toml"), CARGO_TOML);
  writeFileSync(tauriPath(dir, "Cargo.lock"), CARGO_LOCK);
  return dir;
}
