//! The seed reference corpus of idiom / style exemplars.
//!
//! Each [`CorpusEntry`] is a labelled point in embedding space — a known
//! musical idiom (a style or vocabulary) with a representative embedding and
//! human-facing metadata (genre, an exemplar artist, an era). Retrieval
//! ([`crate::retrieve`]) finds the entries nearest a query embedding.
//!
//! ## This is a *seed*, to be expanded
//!
//! The bundled `data/corpus.json` is a small, hand-shaped starter set, not the
//! product. The design doc (`story-phase4-musical-relevance.md` §3B.4) calls
//! for bootstrapping on open datasets (Weimar Jazz Database, Dig That Lick
//! DTL1000, the Parker Omnibook) and growing a labelled catalogue from real
//! sessions over time — *that* catalogue is the moat. The embeddings here are
//! produced by [`crate::embed::BaselineEmbedder`] over synthetic exemplar
//! tones, so they are real-shaped and consistent with query embeddings, but
//! they are placeholders for embeddings of real reference recordings.
//!
//! ## Embeddings are encoder-specific
//!
//! A corpus is only comparable to query vectors from the *same* embedder. The
//! corpus records the dimension; when a MERT-class encoder replaces the
//! baseline, the corpus must be regenerated with it.

use crate::error::IdiomError;
use serde::{Deserialize, Serialize};

/// The seed corpus bundled with the crate as `data/corpus.json`.
const SEED_CORPUS_JSON: &str = include_str!("../data/corpus.json");

/// One labelled idiom/style exemplar in embedding space.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CorpusEntry {
    /// Human-facing idiom name, e.g. `"Bebop line"`, `"Modal / Dorian colour"`.
    pub label: String,
    /// Broad family / genre, e.g. `"jazz"`, `"blues"`, `"classical"`.
    pub genre: String,
    /// A representative artist for this idiom (named, never hosted audio).
    pub exemplar_artist: String,
    /// Rough era, e.g. `"1940s-50s"`, `"1960s"`.
    pub era: String,
    /// The reference embedding for this idiom.
    pub embedding: Vec<f32>,
}

/// A validated collection of [`CorpusEntry`] with a fixed embedding dimension.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Corpus {
    /// Embedding dimension every entry must match (and every query must match).
    pub dim: usize,
    /// The labelled exemplars.
    pub entries: Vec<CorpusEntry>,
}

impl Corpus {
    /// Load and validate the seed corpus bundled with the crate.
    pub fn seed() -> Result<Self, IdiomError> {
        Self::from_json(SEED_CORPUS_JSON)
    }

    /// Parse and validate a corpus from a JSON string.
    pub fn from_json(json: &str) -> Result<Self, IdiomError> {
        let corpus: Corpus =
            serde_json::from_str(json).map_err(|e| IdiomError::CorpusParse(e.to_string()))?;
        corpus.validate()?;
        Ok(corpus)
    }

    /// Number of entries in the corpus.
    pub fn len(&self) -> usize {
        self.entries.len()
    }

    /// Whether the corpus has no entries.
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    /// Validate structural invariants: non-empty, positive dimension, and every
    /// entry's embedding matches `dim`, has finite values, and is labelled.
    pub fn validate(&self) -> Result<(), IdiomError> {
        if self.dim == 0 {
            return Err(IdiomError::CorpusInvalid("embedding dim is 0".into()));
        }
        if self.entries.is_empty() {
            return Err(IdiomError::CorpusInvalid("corpus has no entries".into()));
        }
        for (i, e) in self.entries.iter().enumerate() {
            if e.embedding.len() != self.dim {
                return Err(IdiomError::CorpusInvalid(format!(
                    "entry {i} ({}) has {} dims, expected {}",
                    e.label,
                    e.embedding.len(),
                    self.dim
                )));
            }
            if e.embedding.iter().any(|x| !x.is_finite()) {
                return Err(IdiomError::CorpusInvalid(format!(
                    "entry {i} ({}) has a non-finite embedding value",
                    e.label
                )));
            }
            if e.label.trim().is_empty() {
                return Err(IdiomError::CorpusInvalid(format!(
                    "entry {i} has empty label"
                )));
            }
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::embed::BASELINE_DIM;

    #[test]
    fn seed_corpus_loads_and_validates() {
        let c = Corpus::seed().expect("seed corpus must load");
        assert!(!c.is_empty());
        assert_eq!(c.len(), c.entries.len());
        // The bundled corpus is generated by the baseline embedder.
        assert_eq!(c.dim, BASELINE_DIM);
    }

    #[test]
    fn seed_entries_are_well_formed() {
        let c = Corpus::seed().unwrap();
        for e in &c.entries {
            assert!(!e.label.is_empty());
            assert!(!e.genre.is_empty());
            assert!(!e.exemplar_artist.is_empty());
            assert!(!e.era.is_empty());
            assert_eq!(e.embedding.len(), c.dim);
        }
    }

    #[test]
    fn rejects_empty_corpus() {
        let json = r#"{ "dim": 3, "entries": [] }"#;
        assert!(matches!(
            Corpus::from_json(json),
            Err(IdiomError::CorpusInvalid(_))
        ));
    }

    #[test]
    fn rejects_zero_dim() {
        let json = r#"{ "dim": 0, "entries": [
            { "label": "x", "genre": "g", "exemplar_artist": "a", "era": "e", "embedding": [] }
        ] }"#;
        assert!(matches!(
            Corpus::from_json(json),
            Err(IdiomError::CorpusInvalid(_))
        ));
    }

    #[test]
    fn rejects_dimension_mismatch() {
        let json = r#"{ "dim": 3, "entries": [
            { "label": "x", "genre": "g", "exemplar_artist": "a", "era": "e", "embedding": [1.0, 2.0] }
        ] }"#;
        assert!(matches!(
            Corpus::from_json(json),
            Err(IdiomError::CorpusInvalid(_))
        ));
    }

    #[test]
    fn rejects_non_finite_embedding() {
        // serde_json refuses to parse `inf`/`NaN`, so construct directly and
        // exercise `validate` — the guard protects against a generator (or a
        // future binary-format loader) that emits non-finite values.
        let corpus = Corpus {
            dim: 1,
            entries: vec![CorpusEntry {
                label: "x".into(),
                genre: "g".into(),
                exemplar_artist: "a".into(),
                era: "e".into(),
                embedding: vec![f32::INFINITY],
            }],
        };
        assert!(matches!(
            corpus.validate(),
            Err(IdiomError::CorpusInvalid(_))
        ));
    }

    #[test]
    fn rejects_malformed_json() {
        assert!(matches!(
            Corpus::from_json("{ not json"),
            Err(IdiomError::CorpusParse(_))
        ));
    }

    #[test]
    fn round_trips_through_json() {
        let c = Corpus::seed().unwrap();
        let json = serde_json::to_string(&c).unwrap();
        let back = Corpus::from_json(&json).unwrap();
        assert_eq!(c, back);
    }
}
