// Generated by `supabase gen types typescript` against the ai-music-companion
// project (ref ttcbaomzgoatunjneuan). Regenerate after schema migrations.
// Source of truth for the schema is supabase/migrations/*.sql.
// NOTE: `learner_model` (migration 0005) was added by hand while the project
// is paused — regenerate to confirm once the migration is applied.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      assignments: {
        Row: {
          created_at: string;
          goal: string | null;
          id: string;
          note: string | null;
          score_ref: string | null;
          status: string;
          student_id: string;
          teacher_id: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          goal?: string | null;
          id?: string;
          note?: string | null;
          score_ref?: string | null;
          status?: string;
          student_id: string;
          teacher_id: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          goal?: string | null;
          id?: string;
          note?: string | null;
          score_ref?: string | null;
          status?: string;
          student_id?: string;
          teacher_id?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "assignments_student_id_fkey";
            columns: ["student_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "assignments_teacher_id_fkey";
            columns: ["teacher_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      profiles: {
        Row: {
          age_tier: string | null;
          created_at: string;
          display_name: string | null;
          id: string;
          role: string;
        };
        Insert: {
          age_tier?: string | null;
          created_at?: string;
          display_name?: string | null;
          id: string;
          role?: string;
        };
        Update: {
          age_tier?: string | null;
          created_at?: string;
          display_name?: string | null;
          id?: string;
          role?: string;
        };
        Relationships: [];
      };
      session_phrases: {
        Row: {
          id: string;
          mean_amplitude: number | null;
          phrase_index: number;
          session_id: string;
          stability: number | null;
          tone: Json | null;
        };
        Insert: {
          id?: string;
          mean_amplitude?: number | null;
          phrase_index: number;
          session_id: string;
          stability?: number | null;
          tone?: Json | null;
        };
        Update: {
          id?: string;
          mean_amplitude?: number | null;
          phrase_index?: number;
          session_id?: string;
          stability?: number | null;
          tone?: Json | null;
        };
        Relationships: [
          {
            foreignKeyName: "session_phrases_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "sessions";
            referencedColumns: ["id"];
          },
        ];
      };
      sessions: {
        Row: {
          created_at: string;
          duration_secs: number;
          ended_at: string;
          fingerprint: Json | null;
          id: string;
          instrument: string;
          overall_assessment: string | null;
          phrase_count: number;
          session_tone: Json | null;
          started_at: string;
          student_id: string;
        };
        Insert: {
          created_at?: string;
          duration_secs: number;
          ended_at: string;
          fingerprint?: Json | null;
          id?: string;
          instrument: string;
          overall_assessment?: string | null;
          phrase_count?: number;
          session_tone?: Json | null;
          started_at: string;
          student_id: string;
        };
        Update: {
          created_at?: string;
          duration_secs?: number;
          ended_at?: string;
          fingerprint?: Json | null;
          id?: string;
          instrument?: string;
          overall_assessment?: string | null;
          phrase_count?: number;
          session_tone?: Json | null;
          started_at?: string;
          student_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "sessions_student_id_fkey";
            columns: ["student_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      learner_model: {
        Row: {
          model: Json;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          model: Json;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          model?: Json;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "learner_model_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: true;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      taste_profile: {
        Row: {
          artists: Json;
          experience: string;
          genres: Json;
          goals: Json;
          is_under_13: boolean;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          artists?: Json;
          experience?: string;
          genres?: Json;
          goals?: Json;
          is_under_13?: boolean;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          artists?: Json;
          experience?: string;
          genres?: Json;
          goals?: Json;
          is_under_13?: boolean;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "taste_profile_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: true;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      teacher_student_links: {
        Row: {
          consent_at: string | null;
          consented_by: string | null;
          consenting_adult_id: string | null;
          id: string;
          invited_at: string;
          status: string;
          student_id: string;
          teacher_id: string;
        };
        Insert: {
          consent_at?: string | null;
          consented_by?: string | null;
          consenting_adult_id?: string | null;
          id?: string;
          invited_at?: string;
          status?: string;
          student_id: string;
          teacher_id: string;
        };
        Update: {
          consent_at?: string | null;
          consented_by?: string | null;
          consenting_adult_id?: string | null;
          id?: string;
          invited_at?: string;
          status?: string;
          student_id?: string;
          teacher_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "teacher_student_links_consenting_adult_id_fkey";
            columns: ["consenting_adult_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "teacher_student_links_student_id_fkey";
            columns: ["student_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "teacher_student_links_teacher_id_fkey";
            columns: ["teacher_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};
